apiVersion: v1
kind: Secret
metadata:
  name: videoshare-secret
  namespace: videoshare-prod
  labels:
    app.kubernetes.io/name: videoshare
    environment: production
type: Opaque
stringData:
  MYSQL_USER: "SAdmin"
  MYSQL_PASSWORD: "SuperAdmin@1047"
  SESSION_SECRET_LETTER: "qwoieuroiqwueo42903u0"
  AZURE_STORAGE_ACCOUNT: "cw2videostorage01"
  AZURE_STORAGE_CONNECTION_STRING: "DefaultEndpointsProtocol=https;AccountName=cw2videostorage01;EndpointSuffix=core.windows.net"
