apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: videoshare-media-pvc
  namespace: videoshare-prod
  labels:
    app.kubernetes.io/name: videoshare
    environment: production
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
